apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: gpu-container
          image: nvidia/cuda
          command: ["sh", "-c"]
          resources:
            limits:
              nvidia.com/gpu: 1